# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac575360c4e075d90402e4ba2b622a7cb2acf7dfc5ed02e9ca8b324a5b28e99a4d690e026b02d81de517b3809c6189e8d1c5c3ab75f568df645a027e3ac6ef07

test:
  secret_key_base: 2f828fee43244cfc8afd469e74edb59e6b03ab9608aba2063f6522929998284b9a3c4b813dc79ba2b2b7946cdf06e52bd9c54a5cf5f0b85d033c575a21b3e752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
